import type {
  FileInstructionSection,
  InstructionSection,
  SkillDocumentInput,
  SkillSection,
} from './skill-types.js';

function makeSkillHeader(input: { name: string; description?: string }): string {
  const lines = ['---', `name: ${input.name}`];
  if (input.description) {
    lines.push(`description: ${input.description}`);
  }
  lines.push('---');
  return lines.join('\n');
}

export function renderSkillFrontmatter(input: { name: string; description?: string }): string {
  return `${makeSkillHeader(input)}\n`;
}

export function hasYamlFrontmatter(content: string): boolean {
  return /^---\n[\s\S]*?\n---(?:\n|$)/u.test(content);
}

function hasInstructionPath(instruction: InstructionSection): instruction is FileInstructionSection {
  return instruction.ref !== 'literal';
}

function appendTitledSections(lines: string[], title: string, sections: readonly SkillSection[], mode: 'inline' | 'reference'): void {
  if (sections.length === 0) {
    return;
  }

  lines.push(`## ${title}`);
  lines.push('');
  for (const section of sections) {
    lines.push(`### ${section.ref}`);
    lines.push('');
    lines.push(mode === 'inline' ? section.body : section.path);
    lines.push('');
  }
}

function appendInstructions(lines: string[], sections: readonly InstructionSection[], mode: 'inline' | 'reference'): void {
  if (sections.length === 0) {
    return;
  }

  lines.push('## Instructions');
  lines.push('');
  for (const section of sections) {
    if (mode === 'reference' && hasInstructionPath(section)) {
      lines.push(`### ${section.ref}`);
      lines.push('');
      lines.push(section.path);
    } else {
      lines.push(section.body);
    }
    lines.push('');
  }
}

export function renderSkillDocument(input: SkillDocumentInput): string {
  const lines: string[] = [
    makeSkillHeader(input.definition),
    '',
    '<!-- Generated by faceted-prompting. Do not edit manually. -->',
    '',
    '## Persona',
    '',
    input.mode === 'inline' ? input.persona.body : input.persona.path,
    '',
  ];

  appendTitledSections(lines, 'Policies', input.policies, input.mode);
  appendTitledSections(lines, 'Knowledge', input.knowledge, input.mode);
  appendInstructions(lines, input.instructions, input.mode);

  return `${lines.join('\n').trimEnd()}\n`;
}
