import { DEFAULT_USER_MESSAGE_ORDER } from '../types.js';
import type { ComposeDefinition, ComposeOrderEntry } from '../types.js';
import type {
  FileInstructionSection,
  InstructionSection,
  SkillDocumentInput,
  SkillSection,
} from './skill-types.js';

function makeSkillHeader(definition: ComposeDefinition): string {
  return [
    '---',
    `name: ${definition.name}`,
    ...(definition.description ? [`description: ${definition.description}`] : []),
    '---',
  ].join('\n');
}

export function renderSkillFrontmatter(definition: ComposeDefinition): string {
  return `${makeSkillHeader(definition)}\n`;
}

export function hasYamlFrontmatter(content: string): boolean {
  return /^---\n[\s\S]*?\n---(?:\n|$)/u.test(content);
}

function hasInstructionPath(instruction: InstructionSection): instruction is FileInstructionSection {
  return instruction.ref !== 'literal';
}

function renderSkillSection(title: string, sections: readonly SkillSection[], mode: 'inline' | 'reference'): readonly string[] {
  if (sections.length === 0) {
    return [];
  }

  return [
    `## ${title}`,
    '',
    ...sections.flatMap(section => [
      `### ${section.ref}`,
      '',
      mode === 'inline' ? section.body : section.path,
      '',
    ]),
  ];
}

function renderInstructions(instructions: readonly InstructionSection[], mode: 'inline' | 'reference'): readonly string[] {
  if (instructions.length === 0) {
    return [];
  }

  return [
    '## Instructions',
    '',
    ...instructions.flatMap(instruction => (
      mode === 'reference' && hasInstructionPath(instruction)
        ? [`### ${instruction.ref}`, '', instruction.path, '']
        : [instruction.body, '']
    )),
  ];
}

function renderOrderedSection(input: SkillDocumentInput, entry: ComposeOrderEntry): readonly string[] {
  if (entry === 'knowledge') {
    return renderSkillSection('Knowledge', input.knowledge, input.mode);
  }

  if (entry === 'instructions') {
    return renderInstructions(input.instructions, input.mode);
  }

  if (entry === 'output-contracts') {
    return renderSkillSection('Output Contracts', input.outputContracts, input.mode);
  }

  return renderSkillSection('Policies', input.policies, input.mode);
}

export function renderSkillDocument(input: SkillDocumentInput): string {
  const sectionOrder = input.definition.order ?? DEFAULT_USER_MESSAGE_ORDER;
  const lines = [
    makeSkillHeader(input.definition),
    '',
    '<!-- Generated by faceted-prompting. Do not edit manually. -->',
    '',
    '## Persona',
    '',
    input.mode === 'inline' ? input.persona.body : input.persona.path,
    '',
    ...sectionOrder.flatMap(entry => renderOrderedSection(input, entry)),
  ];

  return `${lines.join('\n').trimEnd()}\n`;
}
